# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GTM_SDC_Plotting.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlottingWindow(object):
    def setupUi(self, PlottingWindow):
        PlottingWindow.setObjectName("PlottingWindow")
        PlottingWindow.resize(1440, 807)
        self.centralwidget = QtWidgets.QWidget(PlottingWindow)
        self.centralwidget.setObjectName("centralwidget")
        PlottingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlottingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 24))
        self.menubar.setObjectName("menubar")
        PlottingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlottingWindow)
        self.statusbar.setObjectName("statusbar")
        PlottingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlottingWindow)
        QtCore.QMetaObject.connectSlotsByName(PlottingWindow)

    def retranslateUi(self, PlottingWindow):
        _translate = QtCore.QCoreApplication.translate
        PlottingWindow.setWindowTitle(_translate("PlottingWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlottingWindow = QtWidgets.QMainWindow()
    ui = Ui_PlottingWindow()
    ui.setupUi(PlottingWindow)
    PlottingWindow.show()
    sys.exit(app.exec_())
