# Generated by Django 4.2.4 on 2023-09-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='GRB')),
                ('position_ra', models.CharField(max_length=20, verbose_name='RA (deg)')),
                ('position_dec', models.CharField(max_length=20, verbose_name='DEC (def)')),
                ('time_trigger', models.CharField(max_length=20, verbose_name='Trigger UTC')),
                ('time_t50', models.CharField(max_length=20, verbose_name='T50 (s)')),
                ('time_t90', models.CharField(max_length=20, verbose_name='T90 (s)')),
            ],
        ),
    ]
