# Generated by Django 4.2.4 on 2023-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grb_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grb',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
