# Generated by Django 4.2.4 on 2023-09-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grb_database', '0002_grb_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grb',
            name='name',
            field=models.CharField(max_length=50, verbose_name='GRB'),
        ),
        migrations.AlterField(
            model_name='grb',
            name='time_trigger',
            field=models.CharField(max_length=50, verbose_name='Trigger UTC'),
        ),
    ]
