# Generated by Django 4.2.4 on 2023-09-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grb_database', '0003_alter_grb_name_alter_grb_time_trigger'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='grb',
            order_with_respect_to='name',
        ),
    ]
