# Generated by Django 4.2.4 on 2023-09-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grb_database', '0004_alter_grb_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grb',
            options={'ordering': ['name']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='grb',
            order_with_respect_to=None,
        ),
    ]
