# Generated by Django 4.2.4 on 2023-09-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grb_database', '0005_alter_grb_options_alter_grb_order_with_respect_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grb',
            old_name='position_dec',
            new_name='position_dec_deg',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='position_ra',
            new_name='position_ra_deg',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='time_t50',
            new_name='time_t50_s',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='time_t90',
            new_name='time_t90_s',
        ),
        migrations.RenameField(
            model_name='grb',
            old_name='time_trigger',
            new_name='time_trigger_utc',
        ),
    ]
